baseURL = 'https://arvaid.github.io/hugo-nyum-example/'
DefaultContentLanguage = "en"
title = 'Hugo-Nyum'
# theme = "nyum"
enableGitInfo = true

[outputs]
    home  = [ "HTML", "JSON"]

[taxonomies]
  category = "categories"